# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManagement', '0002_auto_20170302_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='_internal_comments',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='img_presentation',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='_internal_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='img_presentation',
            field=models.ImageField(blank=True, upload_to='venues/presentationImg/'),
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SessionManagement.Venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='img_venue',
            field=models.ImageField(blank=True, upload_to='venues/locationImg/'),
        ),
    ]
