# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0023_auto_20170314_1139'),
        ('SessionManagement', '0003_auto_20170314_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='assessors',
            field=models.ManyToManyField(to='UserManagement.ExpertProfile'),
        ),
    ]
