# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManagement', '0005_auto_20170314_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
