# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManagement', '0007_venue_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
