# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManagement', '0008_room_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_img',
            field=models.FileField(blank=True, upload_to='venues/locationMap/'),
        ),
    ]
