# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManagement', '0009_venue_map_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='street',
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='directions',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location_info',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
