# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0004_auto_20170315_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='competition_year',
            field=models.CharField(default=2016, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
