# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0023_auto_20170314_1139'),
        ('ApplicationManagement', '0005_auto_20170315_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Team'),
        ),
    ]
