# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0026_auto_20170315_1915'),
        ('ApplicationManagement', '0007_remove_application_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('applicant', 'competition_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('reviewer', 'application')]),
        ),
    ]
