# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0027_remove_studentprofile_team'),
        ('SessionManagement', '0011_auto_20170315_1221'),
        ('ApplicationManagement', '0008_auto_20170315_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_1', models.IntegerField(verbose_name='How helpfull was his/her Feedback')),
                ('category_2', models.IntegerField()),
                ('category_3', models.IntegerField()),
                ('category_4', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=250)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Attendent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionManagement.Session')),
            ],
        ),
    ]
