# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category_2',
            field=models.IntegerField(verbose_name='How personal did you feel the Feedback was'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category_3',
            field=models.IntegerField(verbose_name='How easy was it to put the Feedback into action'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category_4',
            field=models.IntegerField(verbose_name='How clear and elaborate was the Experts Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
