# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0010_auto_20170315_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Declined'), (1, 'Unreviewed'), (2, 'Reviewed'), (3, 'Selected'), (4, 'Accepted')], default=0),
        ),
    ]
