# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0011_auto_20170331_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category_1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category_2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category_3',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category_4',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackComm',
            field=models.IntegerField(blank=True, null=True, verbose_name='How well was the Feedback Communicated?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackQuality',
            field=models.IntegerField(blank=True, null=True, verbose_name='How helpfull was his/her Feedback?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackRelated',
            field=models.IntegerField(blank=True, null=True, verbose_name='How well did the Feedback relate to the Assessment Criteria?'),
        ),
    ]
