# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0031_auto_20170317_2326'),
        ('SessionManagement', '0015_auto_20170331_0107'),
        ('ApplicationManagement', '0012_auto_20170331_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Attendent')),
                ('sesssion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionManagement.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_student', to='UserManagement.Attendent')),
            ],
        ),
    ]
