# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0013_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='score',
            name='sesssion',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
