# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0016_auto_20170403_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 3, 21, 6, 49, 372752, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
