# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0018_auto_20170404_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='continent_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='overall_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
