# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0019_auto_20170404_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
