# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0020_application_application_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='memberreview_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='videoreview_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
