# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0021_auto_20170405_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='continent_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='overall_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Declined'), (1, 'Unreviewed'), (2, 'Reviewed'), (3, 'Selected'), (4, 'Accepted')], default=1),
        ),
    ]
