# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationManagement', '0024_auto_20170405_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='review_status',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'In Review'), (2, 'Reviewed'), (3, 'Selected')], default=1),
        ),
    ]
