# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20170302_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Team'),
        ),
    ]
