# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20170302_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(max_length=10, verbose_name='Duration'),
        ),
    ]
