# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20170303_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Twitter',
            new_name='twitter',
        ),
        migrations.RemoveField(
            model_name='award',
            name='city',
        ),
        migrations.RemoveField(
            model_name='award',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='award',
            name='country',
        ),
        migrations.RemoveField(
            model_name='award',
            name='year',
        ),
        migrations.AddField(
            model_name='award',
            name='Competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Competition'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Award won'),
        ),
    ]
