# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20170303_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Language')),
                ('prof_written', models.IntegerField(choices=[(1, 'basic communcation skills'), (2, 'good command'), (3, 'very good command'), (4, 'excellent command'), (5, 'near native'), (6, 'native speaker')], verbose_name='Written command')),
                ('prof_spoken', models.IntegerField(choices=[(1, 'basic communcation skills'), (2, 'good command'), (3, 'very good command'), (4, 'excellent command'), (5, 'near native'), (6, 'native speaker')], verbose_name='Verbal command')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='measure',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='blog',
            field=models.URLField(blank=True, null=True, verbose_name='Professional Website/Blog'),
        ),
    ]
