# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_auto_20170303_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Account'),
        ),
    ]
