# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_auto_20170305_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='mediation_experience',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='negotiation_experience',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='internships',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mediation_courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='negotiation_courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='slogan',
        ),
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.ExpertProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediationexperience',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.ExpertProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiationexperience',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.ExpertProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='', max_length=250, verbose_name='Your favorite quote up to 250 characters'),
            preserve_default=False,
        ),
    ]
