# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_auto_20170309_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to='profileImg/%Y/%m/%d'),
        ),
    ]
