# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0013_auto_20170309_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
