# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0015_auto_20170309_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='Competition',
            new_name='competition',
        ),
    ]
