# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0017_team_teamimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('negotiation', 'Negotiation'), ('mediation', 'Mediation'), ('arbitration', 'Arbitratiion')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
