# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0018_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
            preserve_default=False,
        ),
    ]
