# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0019_language_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('negotiation', 'Negotiation'), ('mediation', 'Mediation'), ('arbitration', 'Arbitratiion')], max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='When does your Program start')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='When does your Program end')),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('duration', models.IntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.ExpertProfile')),
            ],
        ),
    ]
