# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0020_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='webpage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
