# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0022_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City of Residence'),
        ),
    ]
