# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0023_auto_20170314_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='attendent_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendent',
            name='role',
            field=models.CharField(choices=[('negotiator', 'Negotiator'), ('mediator', 'Mediator'), ('expert', 'Expert Assessor'), ('coach', 'Coach'), ('assessor', 'Assessor'), ('team', 'Team')], max_length=35),
        ),
    ]
