# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0025_attendent_uni_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendent',
            name='uni_team',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teammembers', to='UserManagement.Attendent'),
        ),
    ]
