# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0027_remove_studentprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='iba_member',
            field=models.BooleanField(default=False, verbose_name='Are you Member of IBA?'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='imi_certified',
            field=models.BooleanField(default=False, verbose_name='Are you IMI Certified?'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='viac_member',
            field=models.BooleanField(default=False, verbose_name='Are you Member of VIAC?'),
        ),
    ]
