# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0029_course_institution_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
        ),
    ]
