# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0030_auto_20170317_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
        ),
    ]
