# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0031_auto_20170317_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('attendent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent')),
            ],
            bases=('UserManagement.attendent',),
        ),
    ]
