# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0032_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('attendent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent')),
            ],
            bases=('UserManagement.attendent',),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Student'),
        ),
    ]
