# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0033_auto_20170405_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='Attendent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Attendent'),
        ),
        migrations.AlterField(
            model_name='attendent',
            name='role',
            field=models.CharField(choices=[('negotiator', 'Negotiator'), ('mediator', 'Mediator'), ('assessor', 'Assessor'), ('mediator', 'Mediator'), ('staff', 'Staff Member'), ('session_management', 'Session Management'), ('expert_feedback', 'Expert Feedback')], max_length=35),
        ),
    ]
