# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0034_auto_20170408_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Attendent',
            new_name='attendent',
        ),
    ]
