# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0036_staff_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofile',
            old_name='team',
            new_name='coachedTeam',
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Team'),
        ),
        migrations.AlterField(
            model_name='attendent',
            name='role',
            field=models.CharField(choices=[('negotiator', 'Negotiator'), ('mediator', 'Mediator'), ('assessor', 'Assessor'), ('staff', 'Staff Member'), ('session_management', 'Session Management'), ('expert_feedback', 'Expert Feedback')], max_length=35),
        ),
    ]
