# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0037_auto_20170408_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
    ]
