# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0038_remove_studentprofile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='profileImg/%Y/%m/%d'),
        ),
    ]
