# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0039_auto_20170409_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='measure',
            field=models.CharField(choices=[('day', 'Days'), ('hour', 'Hours')], max_length=10, verbose_name='Day/Hour'),
        ),
    ]
