# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0040_auto_20170409_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile'),
        ),
    ]
