# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0041_auto_20170409_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='profile',
        ),
    ]
